### ISSUE TITLE
efivars unreadable?

### ISSUE THREAD

**Issue by Joomsy** [xanmod/linux#403]
Starting with version 6.5.3, `efibootmgr` and `kernelstub` both fail to interact with EFI variables for some reason. When running `kernelstub`, this error is generated:
```
EFI variables are not supported on this system.
kernelstub.NVRAM     : ERROR    Failed to retrieve NVRAM data. Are you running in a chroot?
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kernelstub/nvram.py", line 54, in get_nvram
    return subprocess.check_output(command).decode('UTF-8').split('\n')
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['efibootmgr']' returned non-zero exit status 2.
```
When running `efibootmgr`, I get the same notice:
```
> $ sudo efibootmgr                                                                                     
EFI variables are not supported on this system.
```
I've swapped back to the stock kernel from my distribution to test whether or not it's an issue with Xanmod, and that appears to be the case. Other than not being able to actually manipulate the boot order, though, I'm not sure of the extent of this issue. `kernelstub` still sets a new kernel, so it's "working". `/sys/firmware/efi/efivars` also has the expected content. If there's any way I can provide more info, though, do please let me know.

System info:
```
OS: Pop!_OS 22.04 LTS x86_64
Host: MacBookPro11,5 1.0
Kernel: 6.5.4-x64v1-xanmod1
CPU: Intel i7-4980HQ (8) @ 4.000GHz
```

**Comment by Joomsy** [comment]
Interestingly enough, this may have been due to the stock kernel. It itself was just updated to 6.5.4, and this error no longer appears when using anything that calls `efibootmgr`. I'll close this for now, but hopefully won't need to return.
